GlobalPlanner:
#  old_navfn_behavior: false
  use_quadratic: false
  use_dijkstra: true 
  use_grid_path: true

  allow_unknown: false

  default_tolerance: 0.3  

  lethal_cost: 253
  neutral_cost: 50  
  cost_factor: 0.2



