GlobalPlanner:
  allow_unknown: true
  use_dijkstra: false
  use_quadratic: true
  visualize_potential: false
  default_tolerance: 0.3
  neutral_cost: 50
  lethal_cost_threshold: 100
  planner_window_x: 3.0
  planner_window_y: 3.0
  orientation_mode: 2
  cost_factor: 0.3
  obstacle_range: 2.5
  goal_distance_bias: 0.8

