move_base:
  
  base_global_planner: "global_planner/GlobalPlanner" 

  # Global costmap settings
  global_costmap:
    global_frame: "/map"
    robot_base_frame: "/base_footprint"
    static_map: true
    update_frequency: 3.0
    publish_frequency: 1.0
    transform_tolerance: 3.0
    observation_sources: /pepper_robot/naoqi_driver/laser
    footprint: [[-0.242,-0.212], [0.242, -0.212], [0, 0.213]]
    plugins:
      - {name: static_layer, type: "costmap_2d::StaticLayer"}
      - {name: inflation, type: "costmap_2d::InflationLayer"}

    inflation_layer:
      inflation_radius: 0.2
      cost_scaling_factor: 5.0
      max_obstacle_height: 0.3       
      min_obstacle_height: 0.0  
    
 
