GlobalPlanner:
  allow_unknown: true
  use_dijkstra: true 
  use_quadratic: true
  default_tolerance: 0.2  
  neutral_cost: 50  
  lethal_cost_threshold: 250  
  cost_factor: 0.5 
  obstacle_range: 1.5  
  goal_distance_bias: 0.9  
  orientation_mode: 1 

