global_costmap:
  global_frame: /map  
  robot_base_frame: /odom
  transform_tolerance: 0.6
  robot_radius: 0.5
  update_frequency: 5.0
  publish_frequency: 2.0
  rolling_window: false

  width: 40.0
  height: 40.0
  resolution: 0.050000
  origin_x: -10.000000
  origin_y: -10.000000

  footprint: [[-0.2425, 0.0], [0.2425, 0.0], [0.0, 0.425]]

  plugins:
    - {name: static, type: "costmap_2d::StaticLayer"}
    - {name: speed_adjustment_layer, type: "costmap_2d::StaticLayer"}

  static:
    unknown_cost_value: -1
    lethal_cost_threshold: 100
    map_topic: /map  


  speed_adjustment_layer:  
    map_file: /home/humanoidrobots/pepper/src/navigation/maps/speed_layer.yaml
    unknown_cost_value: -1
    lethal_cost_threshold: 100

