move_base:
  
  base_global_planner: "global_planner/GlobalPlanner" 

  # Global costmap settings
  global_costmap:
    global_frame: /map
    robot_base_frame: /base_footprint
    update_frequency: 0.5
    publish_frequency: 0.5
    static_map: true
    transform_tolerance: 2.0
    observation_sources: /pepper_robot/naoqi_driver/laser
    robot_radius: 0.48
#    footprint: [[0.2425, 0.0], [-0.2125, 0.2125], [-0.2125, -0.2125]]


    plugins:
      - {name: static_layer, type: "costmap_2d::StaticLayer"}
      - {name: test_layer_1, type: "test_layer::TestLayer"}
      - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
#      - {name: "right_side_layer", type: "right_side_layer::RightSideLayer" }



    test_layer_1:
      enabled: true
      min_x: -0.5
      min_y: -0.5      
      max_x: 0.5     
      max_y: 2.0
      cost_value: 0


    inflation_layer:
      enabled: true
      inflation_radius: 0.3
      cost_scaling_factor: 0.5
      inflate_unknown: false
      max_obstacle_height: 3.0       
      min_obstacle_height: 0.1 

#    right_side_layer:
#      enabled: true
#      bias_factor: 200  
#      inflation_radius: 0.0
#      outer_radius: 0.5
