local_costmap:
  global_frame: /odom
  robot_base_frame: /base_link
  transform_tolerance: 0.6
  robot_radius: 0.5
  update_frequency: 10.0
  publish_frequency: 5.0
  rolling_window: true

  width: 6.0
  height: 6.0
  resolution: 0.050000
  footprint: [[-0.2425, 0.0], [0.2425, 0.0], [0.0, 0.425]]  

  plugins:
    - {name: static, type: "costmap_2d::StaticLayer"}
    - {name: speed_adjustment_layer, type: "costmap_2d::StaticLayer"}

  static:
    unknown_cost_value: -1
    lethal_cost_threshold: 100
    map_topic: /map_local

  speed_adjustment_layer:  
    map_file: /home/humanoidrobots/pepper/src/navigation/maps/speed_layer.yaml
    unknown_cost_value: -1
    lethal_cost_threshold: 100


 
