move_base:
  
  base_local_planner: "base_local_planner/TrajectoryPlannerROS"  

  local_costmap:
    global_frame: "/odom"
    robot_base_frame: "/base_footprint"
    update_frequency: 2.0  # Reduce CPU load
    publish_frequency: 2.0
    static_map: false
    rolling_window: true
    width: 2.5  
    height: 2.5
    resolution: 0.05
    transform_tolerance: 3.0


    footprint: [[-0.242,-0.212], [0.242, -0.212], [0, 0.213]]

    plugins:
      - {name: static_layer, type: "costmap_2d::StaticLayer"}
      - {name: inflation, type: "costmap_2d::InflationLayer"}
#      - { name: "right_side_layer", type: "right_side_layer_namespace::RightSideLayer" }

    inflation_layer:
      inflation_radius: 0.25  
      cost_scaling_factor: 4.0
      max_obstacle_height: 0.5
      min_obstacle_height: 0.0
 



  # Trajectory Planner settings (Replaces DWAPlanner)
  TrajectoryPlannerROS:
    meter_scoring: true

    max_vel_x: 0.4  
    min_vel_x: 0.05  

    max_vel_theta: 0.2  
    min_vel_theta: 0.1  
    acc_lim_x: 0.5    
    acc_lim_theta: 1.0
    
    yaw_goal_tolerance: 0.3
    xy_goal_tolerance: 0.3  
    latch_xy_goal_tolerance: true  

    sim_time: 1.0 
    sim_granularity: 0.075 
    angular_sim_granularity: 0.05  
    vx_samples: 8 
    vtheta_samples: 20  

# These scales determine how much the planner avoids high cost areas: 
    pdist_scale: 0.5  
    gdist_scale: 0.7  
    occdist_scale: 2.5  

    heading_lookahead: 0.325  
    heading_scoring: false  
    heading_scoring_timestep: 0.8
    dwa: true  

    prune_plan: true  
    oscillation_reset_dist: 0.1 
    clearing_rotation_allowed: false  
