move_base:
  
  base_local_planner: "base_local_planner/TrajectoryPlannerROS"  

  local_costmap:
    global_frame: "/odom"
    robot_base_frame: "/base_footprint"
    update_frequency: 3.0  # Reduce CPU load
    publish_frequency: 2.0
    static_map: false
    rolling_window: true
    width: 3.0  
    height: 3.0
    resolution: 0.05
    transform_tolerance: 3.0

    footprint: [[-0.242,-0.212], [0.242, -0.212], [0, 0.213]]

    plugins:
      - {name: static_layer, type: "costmap_2d::StaticLayer"}
      - {name: inflation, type: "costmap_2d::InflationLayer"}
#      - {name: speed_filter_layer, type: "speed_filter_layer::SpeedFilterLayer"}

    inflation_layer:
      inflation_radius: 0.3  # Smoother obstacle clearance
      cost_scaling_factor: 5.0
      max_obstacle_height: 0.5
      min_obstacle_height: 0.0  

  # Trajectory Planner settings (Replaces DWAPlanner)
  TrajectoryPlannerROS:

    max_vel_x: 0.9  
    min_vel_x: 0.1  
    max_vel_y: 0.0  
    min_vel_y: 0.0  

    max_vel_theta: 0.3  
    min_vel_theta: 0.1  

    acc_lim_x: 0.8  
    acc_lim_y: 0.0  
    acc_lim_theta: 1.0
    
    
    yaw_goal_tolerance: 0.05
    xy_goal_tolerance: 0.05  
    latch_xy_goal_tolerance: false  

    sim_time: 1.5  
    sim_granularity: 0.025  
    angular_sim_granularity: 0.025  
    vx_samples: 8 
    vtheta_samples: 20  

    meter_scoring: true  
    pdist_scale: 0.6  
    gdist_scale: 0.8  
    occdist_scale: 0.02  # Lower influence of obstacles on speed (handle it in SpeedFilterLayer)


    heading_lookahead: 0.325  
    heading_scoring: false  
    heading_scoring_timestep: 0.8
    dwa: true  

    prune_plan: true  
    oscillation_reset_dist: 0.05  
    clearing_rotation_allowed: false  
