move_base:
  # Global planner
  base_global_planner: "global_planner/GlobalPlanner"

  # Dummy local planner using TrajectoryPlannerROS
  base_local_planner: "dwa_local_planner/DWAPlannerROS"

  # Global costmap settings
  global_costmap:
    global_frame: "/map"
    robot_base_frame: "/base_link"
    static_map: true
    update_frequency: 1.0
    transform_tolerance: 1.0

    plugins:
      - {name: static_layer, type: "costmap_2d::StaticLayer"}
      - {name: inflation, type: "costmap_2d::InflationLayer"}

    # Inflation layer settings
    inflation_layer:
      inflation_radius: 0.2  
      cost_scaling_factor: 10.0   

  # Local costmap settings (even if we're not using it, it still needs to be defined)
  local_costmap:
    global_frame: "/odom"
    robot_base_frame: "/base_link"
    update_frequency: 5.0
    publish_frequency: 5.0
    static_map: false
    rolling_window: true
    width: 3.0  # Define size of the local costmap
    height: 3.0
    resolution: 0.05
    transform_tolerance: 0.5

  # Goal tolerance settings
  planner_patience: 5.0
  max_planning_retries: 4

  # Recovery behaviors
  recovery_behaviors: []

  # Parameters for DWAPlannerROS
  DWAPlannerROS:
    # Robot velocity limits
    max_vel_x: 0.9
    min_vel_x: 0.1
    max_vel_theta: 3.0
    min_vel_theta: 0.2
    acc_lim_x: 2.5
    acc_lim_theta: 3.2

    # Goal tolerance
    yaw_goal_tolerance: 0.2
    xy_goal_tolerance: 0.2

    # Trajectory scoring
    path_distance_bias: 24.0 # Prioritize following the global path
    goal_distance_bias: 20.0
    occdist_scale: 0.05  # Reduce to allow paths closer to obstacles

    # Forward simulation
    sim_time: 2.0 # Increase to test longer paths
    vx_samples: 20
    vtheta_samples: 40

    # Oscillation prevention
    oscillation_reset_dist: 0.05

